sudo: required
services:
  - docker
before_install:
  - docker build -t dimohg/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true USERNAME/react-test npm test

after_success:
  - docker build -t dimohg/multi-client ./client
  - docker build -t dimohg/multi-nginx ./nginx
  - docker build -t dimohg/multi-server ./server
  - docker build -t dimohg/multi-worker ./worker
# log in to docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --pasword-stdin
# push to docker hub
  - docker push dimohg/multi-client
  - docker push dimohg/multi-nginx
  - docker push dimohg/multi-server
  - docker push dimohg/multi-worker





